language/urls.py
from django.urls import path

from . import views

# app_name = 'language'
# urlpatterns = [
#     # ex: /polls/
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

app_name = 'language'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('burarra/', views.burarra, name='burarra'),
    path('warlpiri/', views.warlpiri, name='warlpiri'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

wengga/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
	path('', views.landing),
    path('language/', include('language.urls')),
    path('admin/', admin.site.urls),
]

language/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Phrase(models.Model):

    phrase_text = models.CharField(max_length=200)

    def __str__(self):
        return self.phrase_text

class Burarra(models.Model):

    phrase = models.ForeignKey(Phrase, on_delete=models.CASCADE)
    translation_text = models.CharField(max_length=200)
    
    def __str__(self):
        return self.translation_text

class Warlpiri(models.Model):

    phrase = models.ForeignKey(Phrase, on_delete=models.CASCADE)
    translation_text = models.CharField(max_length=200)
    
    def __str__(self):
        return self.translation_text




          

language/forms.py
from django import forms

class TextForm(forms.Form):
    translation = forms.CharField(label='Translation', max_length=300)
    translation.widget.attrs.update({'id' : 'your_id', 'value' : "", 'class' : 'form-control', 'placeholder' : "Write Translation", 'rows' :"4"})

class FileForm(forms.Form):
	file = forms.FileField()

language/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Choice, Question, Phrase, Burarra
import random
from .forms import TextForm
from django.shortcuts import redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.files import File
import sys
from .gap import *


# Create your views here.

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'language/index.html', context)

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'language/detail.html', {'question': question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'language/results.html', {'question': question})

phrase = random.choice(Phrase.objects.all())

def burarra(request):
    global phrase

    if request.method == 'POST':
        form_p = TextForm(request.POST)
        if form_p.is_valid():
            # Translation Text Upload
            print(form_p.cleaned_data['translation'])
            phrase_instance = Phrase(phrase_text=phrase)
            phrase_instance.save()
            burarra_translation = Burarra.objects.create(phrase=phrase_instance, translation_text=form_p.cleaned_data['translation'])
            burarra_translation.save()
            # phrase = random.choice(Phrase.objects.all())
            phrase = critical_phrase()
            form = TextForm(request.POST)
            context = {
            'phrase' : phrase,
            'form':form
            }
            #return render(request, 'language/burarra.html', context)
            return redirect('/language/burarra')

    if request.method == 'POST':
        if request.method == 'POST' and request.FILES['myfile']:
            print("saving file...")
            myfile = request.FILES['myfile']
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            # phrase = random.choice(Phrase.objects.all())
            phrase = critical_phrase()
            form = TextForm(request.POST)
            context = {
            'phrase' : phrase,
            'form':form
            }
            #return render(request, 'language/burarra.html', context)
            return redirect('/language/burarra')

    # phrase = random.choice(Phrase.objects.all())
    phrase = critical_phrase()
    form = TextForm(request.POST)
    context = {
    'phrase' : phrase,
    'form':form
    }        
    return render(request, 'language/burarra.html', context)

def warlpiri(request):
    context = {
    }
    return render(request, 'language/warlpiri.html', context)


class IndexView(generic.ListView):
    template_name = 'language/index.html'
    # overriding automatic variable name ("question_list")
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'language/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'language/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'language/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('language:results', args=(question.id,)))

wengga/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return HttpResponse("Welcome! Please select the language you would like to translate")

def landing(request):
	context = {
	}
	return render(request, 'landing/index.html', context)

language/templates/language/burarra.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
  	<style>

  	.square{
    width: 370px;
    height: 300px;
    border-style: solid;
    font-family: Arial,Helvetica Neue,Helvetica,sans-serif; 
    Background-color: #fff;/* Your Color */
	}

	</style>


    <!--meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Bootstrap, Landing page, Template, Business, Service">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Grayrids">
    <title>Wengga</title>
    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon" href="{% static 'land/img/2.png' %}" type="image/png">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'land/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/LineIcons.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/nivo-lightbox.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/responsive.css' %}">

 	</head>
 

  <body>

    <!-- Header Section Start -->
    <header id="home" class="hero-area">    
      <div class="overlay">
        <span></span>
        <span></span>
      </div>
      <nav class="navbar navbar-expand-md bg-inverse fixed-top scrolling-navbar">
        <div class="container">
          <a href="index.html" class="navbar-brand"><img src="{% static 'land/img/logo.png' %}" alt=""></a>       
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <i class="lni-menu"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto w-100 justify-content-end">
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/#home">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/#services">About</a>
              </li>  
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/#features">Languages</a>
              </li>                            
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/#new_language">New Language</a>
              </li>  
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/#contact">Contact</a>
              </li> 
              <li class="nav-item">
                <a class="btn btn-singin page-scroll" href="/#features">Contribute</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>  
      <!-- Contact Us Section -->
    <section id="contact" class="section">
      <!-- Container Starts -->
      <div class="container">
        <!-- Start Row -->
        <div class="row">
          <div>
            <div class="contact-text section-header text-center">  
              <div>   
                <h3 class="section-title">Transate the Phrase Below to Burarra</h2>
                <div class="desc-text">
                </div>
              </div> 
            </div>
          </div>

        </div>
        <!-- End Row -->
        <!-- Start Row -->
        <div class="row">

         <!-- Start Col -->

         <div class="square" align="center" ><font color="black" size="6"> <u>Translate the Following: </u></br> {{phrase}} </font></div>

          <!-- End Col -->
    <!-- Start Col -->
          <div class="col-lg-1">
            
          </div>
          <!-- End Col -->

          <!-- Start Col -->
          <div class="col-lg-1">
          </div>
          <!-- End Col -->
          <!-- Start Col -->
          <div class="col-lg-6 col-md-12">
            <div class="row">
  
             <div class="col-md-12">
               
              <h4>Provide the Translation Below</h4>

              <form action="" method="post">
                  {% csrf_token %}
                  {{ form }}
                  <div class="submit-button">
                  </br>
                  <button class="btn btn-common" id="submit" type="Submit">Submit</button>
                  <div id="msgSubmit" class="h3 hidden"></div> 
              </form>
                
              </div>

            </div>            

          </div>
          <!-- End Col -->

          
            <br> <br> <br> <br> <br> <br> 
            <h4>Upload Translated Text Files</h4>
            {% block content %}
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="myfile">
                <button type="submit">Upload</button>
              </form>
            {% endblock %}

        </div>
        <!-- End Row -->
      </div>
    </section>
    <!-- Contact Us Section End -->
    <!-- Header Section End --> 
  
    <!-- Footer Section Start -->
    <footer>
      <!-- Footer Area Start -->
      <section id="footer-Content">
        <div class="container">
          <!-- Start Row -->
          <div class="row">

          <!-- Start Col -->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              
              <div class="footer-logo">
               <img src="{% static 'land/img/logo.png' %}" alt="">
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Begin</h3>
                <ul class="menu">
                  <li><a href="#">  - Develop Language</a></li>
                  <li><a href="#">- New Language</a></li>
                </ul>
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Languages</h3>
                <ul class="menu">
                  <li><a href="#">  - Customer Service</a></li>
                  <li><a href="#">- Enterprise</a></li>
                </ul>
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Download App</h3>
                <ul class="menu">
                  <li><a href="#">  - Android App</a></li>
                  <li><a href="#">- IOS App</a></li>
                </ul>
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Subscribe Now</h3>
                <p> Keep up-to-date with new language translation projects and initiatives </p>
                <div class="subscribe-area">
                  <input type="email" class="form-control" placeholder="Enter Email">
                  <span><i class="lni-chevron-right"></i></span>
                </div>
              </div>
            </div>
            <!-- End Col -->
          </div>
          <!-- End Row -->
        </div>
        <!-- Copyright Start  -->

        <div class="copyright">
          <div class="container">
            <!-- Star Row -->
            <div class="row">
              <div class="col-md-12">
                <div class="site-info text-center">
                  <p>See More <a href="https://www.bishopcolton.com">Projects</a></p>
                </div>              
                
              </div>
              <!-- End Col -->
            </div>
            <!-- End Row -->
          </div>
        </div>
      <!-- Copyright End -->
      </section>
      <!-- Footer area End -->
      
    </footer>
    <!-- Footer Section End --> 

    <!-- Go To Top Link -->
    <a href="#" class="back-to-top">
      <i class="lni-chevron-up"></i>
    </a> 

    <!-- Preloader -->
    <div id="preloader">
      <div class="loader" id="loader-1"></div>
    </div>
    <!-- End Preloader -->

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="{% static 'land/js/jquery-min.js' %}"></script>
    <script src="{% static 'land/js/popper.min.js' %}"></script>
    <script src="{% static 'land/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'land/js/owl.carousel.js' %}"></script>      
    <script src="{% static 'land/js/jquery.nav.js' %}"></script>    
    <script src="{% static 'land/js/scrolling-nav.js' %}"></script>    
    <script src="{% static 'land/js/jquery.easing.min.js' %}"></script>     
    <script src="{% static 'land/js/nivo-lightbox.js' %}"></script>     
    <script src="{% static 'land/js/jquery.magnific-popup.min.js' %}"></script>      
    <script src="{% static 'land/js/main.js' %}"></script>


  </body>
</html>

language/templates/language/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'language:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

language/templates/language/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
  	<style>

  	.square{
    width: 370px;
    height: 300px;
    Background-color: #fff;/* Your Color */
	}

	</style>


    <!--meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Bootstrap, Landing page, Template, Business, Service">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="author" content="Grayrids">
    <title>Wengga</title>
    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon" href="{% static 'land/img/2.png' %}" type="image/png">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'land/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/LineIcons.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/nivo-lightbox.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'land/css/responsive.css' %}">
 	</head>
 

  <body>

    <!-- Header Section Start -->
    <header id="home" class="hero-area">    
      <div class="overlay">
        <span></span>
        <span></span>
      </div>
      <nav class="navbar navbar-expand-md bg-inverse fixed-top scrolling-navbar">
        <div class="container">
          <a href="index.html" class="navbar-brand"><img src="{% static 'land/img/logo.png' %}" alt=""></a>       
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <i class="lni-menu"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto w-100 justify-content-end">
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/#home">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/#services">About</a>
              </li>  
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/#features">Languages</a>
              </li>                            
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/#new_language">New Language</a>
              </li>  
              <li class="nav-item">
                <a class="nav-link page-scroll" href="/#contact">Contact</a>
              </li> 
              <li class="nav-item">
                <a class="btn btn-singin page-scroll" href="/#features">Contribute</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>  
      <!-- Contact Us Section -->
    <section id="contact" class="section">
      <!-- Container Starts -->
      <div class="container">
        <!-- Start Row -->
        <div class="row">
          <div>
            <div class="contact-text section-header text-center">  
              <div>   
                <h3 class="section-title">Transate the Phrase Below</h2>
                <div class="desc-text">
                </div>
              </div> 
            </div>
          </div>

        </div>
        <!-- End Row -->
        <!-- Start Row -->
        <div class="row">

         <!-- Start Col -->

         <div class="square" align="center" ><font color="black" size="6"> <u>Translate the Following: </u></br> The cat fought against the dog. </font></div>

          <!-- End Col -->
    <!-- Start Col -->
          <div class="col-lg-1">
            
          </div>
          <!-- End Col -->

          <!-- Start Col -->
          <div class="col-lg-1">
          </div>
          <!-- End Col -->
          <!-- Start Col -->
          <div class="col-lg-6 col-md-12">
          <form id="contactForm">
            <div class="row">
  
              <div class="col-md-12">
                <div class="form-group"> 
                  <textarea class="form-control" id="message"  name="message" placeholder="Write Message" rows="4" data-error="Write your message" required></textarea>
                  <div class="help-block with-errors"></div>
                </div>
                <div class="submit-button">
                  <button class="btn btn-common" id="submit" type="submit">Submit</button>
                  <div id="msgSubmit" class="h3 hidden"></div> 
                  <div class="clearfix"></div> 
                </div>
              </div>
            </div>            
          </form>
          </div>
          <!-- End Col -->
          

        </div>
        <!-- End Row -->
      </div>
    </section>
    <!-- Contact Us Section End -->
    <!-- Header Section End --> 
  
    <!-- Footer Section Start -->
    <footer>
      <!-- Footer Area Start -->
      <section id="footer-Content">
        <div class="container">
          <!-- Start Row -->
          <div class="row">

          <!-- Start Col -->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              
              <div class="footer-logo">
               <img src="{% static 'land/img/logo.png' %}" alt="">
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Begin</h3>
                <ul class="menu">
                  <li><a href="#">  - Develop Language</a></li>
                  <li><a href="#">- New Language</a></li>
                </ul>
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Languages</h3>
                <ul class="menu">
                  <li><a href="#">  - Customer Service</a></li>
                  <li><a href="#">- Enterprise</a></li>
                </ul>
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-2 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Download App</h3>
                <ul class="menu">
                  <li><a href="#">  - Android App</a></li>
                  <li><a href="#">- IOS App</a></li>
                </ul>
              </div>
            </div>
             <!-- End Col -->
              <!-- Start Col -->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="block-title">Subscribe Now</h3>
                <p> Keep up-to-date with new language translation projects and initiatives </p>
                <div class="subscribe-area">
                  <input type="email" class="form-control" placeholder="Enter Email">
                  <span><i class="lni-chevron-right"></i></span>
                </div>
              </div>
            </div>
            <!-- End Col -->
          </div>
          <!-- End Row -->
        </div>
        <!-- Copyright Start  -->

        <div class="copyright">
          <div class="container">
            <!-- Star Row -->
            <div class="row">
              <div class="col-md-12">
                <div class="site-info text-center">
                  <p>See More <a href="https://www.bishopcolton.com">Projects</a></p>
                </div>              
                
              </div>
              <!-- End Col -->
            </div>
            <!-- End Row -->
          </div>
        </div>
      <!-- Copyright End -->
      </section>
      <!-- Footer area End -->
      
    </footer>
    <!-- Footer Section End --> 


    <!-- Go To Top Link -->
    <a href="#" class="back-to-top">
      <i class="lni-chevron-up"></i>
    </a> 

    <!-- Preloader -->
    <div id="preloader">
      <div class="loader" id="loader-1"></div>
    </div>
    <!-- End Preloader -->

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="{% static 'land/js/jquery-min.js' %}"></script>
    <script src="{% static 'land/js/popper.min.js' %}"></script>
    <script src="{% static 'land/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'land/js/owl.carousel.js' %}"></script>      
    <script src="{% static 'land/js/jquery.nav.js' %}"></script>    
    <script src="{% static 'land/js/scrolling-nav.js' %}"></script>    
    <script src="{% static 'land/js/jquery.easing.min.js' %}"></script>     
    <script src="{% static 'land/js/nivo-lightbox.js' %}"></script>     
    <script src="{% static 'land/js/jquery.magnific-popup.min.js' %}"></script>      
    <script src="{% static 'land/js/main.js' %}"></script>


  </body>
</html>

language/templates/language/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'language:detail' question.id %}">Vote again?</a>

templates/home/download.html
{% block content %}
  <form action="download_pic/{{image.objname}}" method="post" >
    {% csrf_token %}
    <button type="submit" value={{image.name}}">Convert to Mesh!</button>
  </form>

{% endblock %}